### ISSUE TITLE
not able to install tools for html5

### ISSUE THREAD

**Issue by debasishparida** [MovalysMDK/mdk-cli#1]
Hello I am using the following command 
mdk tools-install html5.

But I am getting the following error

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by SupportMovalys** [comment]
Hello,

I cannot reproduce that problem.
Could you please give me the following information:
-   What OS are you on?
-   What version of mdk-cli are you running (found with the command 'mdk version’)

Best regards

Simon

De : debasishparida <notifications@github.com<mailto:notifications@github.com>>
Répondre à : MovalysMDK/mdk-cli <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : lundi 8 août 2016 12:33
À : MovalysMDK/mdk-cli <mdk-cli@noreply.github.com<mailto:mdk-cli@noreply.github.com>>
Objet : [MovalysMDK/mdk-cli] not able to install tools for html5 (#1)

Hello I am using the following command
mdk tools-install html5.

But I am getting the following error

events.js:141
throw er; // Unhandled 'error' event
^

Error: spawn git ENOENT
at exports._errnoException (util.js:873:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

**Comment by debasishparida** [comment]
Hello,
I am on windows 7
The version of the MDK is 1.1.7

regards,
Debasish

**Comment by ghost** [comment]
Hello,

I am sorry, could you please also tell me the node.js version you are running?

Best regards

Simon

**Comment by debasishparida** [comment]
Hello, 
when i executed the "npm -version" command ti gives me the version 2.15.8
the "node -v" gives version is 4.4.7

regards,
Debasish

**Comment by ghost** [comment]
This error seems to be more npm related than specific to the mdk-cli tool.
From what I've found out googling that, it seems running 
`npm cache clean`
may fix this.

Waiting fior your feedback.

Simon

**Comment by debasishparida** [comment]
i executed the "npm cache clean" and then i am executing "mdk tools-install html5" still getting the same error.

**Comment by ghost** [comment]
To sum up, this problem occurs because some call to `spawn`, which is used to execute a command, results in an error.
The problem here is that `spawn`does not give any clue on which command it is trying to execute when it fails.

In order to find out which command is causing this issue, I have patched the mdk.js file.
It will now give more information about the command `spawn` is trying to execute.

Please replace the mdk.js file found at `C:\<Username>\AppData\Roaming\npm\node_modules\mdk-cli\lib` by the one attached to my answer (after unzipping it), run the `mdk tools-install html5` command again and give me the last few lines displayed on your shell.

[mdk.zip](https://github.com/MovalysMDK/mdk-cli/files/412805/mdk.zip)
